import { PrismaClient } from '@prisma/client';
import { authService } from '../auth/authService';

const prisma = new PrismaClient();

export interface CreateInvitationData {
  email: string;
  organizationId: string;
  roleId?: string;
  invitedBy: string;
}

export interface Invitation {
  id: string;
  email: string;
  organizationId: string;
  roleId: string | null;
  token: string;
  invitedBy: string;
  accepted: boolean;
  expiresAt: Date;
  createdAt: Date;
}

/**
 * Team Invitation Service
 * Handles user invitations for team management
 */
export class InvitationService {
  /**
   * Create a new invitation
   */
  async createInvitation(data: CreateInvitationData): Promise<Invitation> {
    // Check if user already exists
    const existingUser = await prisma.user.findUnique({
      where: { email: data.email },
    });

    if (existingUser) {
      throw new Error('User with this email already exists');
    }

    // Generate invitation token
    const token = authService.generateSecureToken();
    const expiresAt = new Date();
    expiresAt.setDate(expiresAt.getDate() + 7); // 7 days expiry

    // Create invitation record
    // Note: We'll need to add an Invitation model to the schema
    // For now, this is a placeholder that shows the structure
    // TODO: Add Invitation model to Prisma schema
    
    // For now, we'll use a simple approach - store in a JSON field or create the model
    // This is a conceptual implementation
    const invitation = {
      id: '', // Will be generated by Prisma
      email: data.email,
      organizationId: data.organizationId,
      roleId: data.roleId || null,
      token: token,
      invitedBy: data.invitedBy,
      accepted: false,
      expiresAt: expiresAt,
      createdAt: new Date(),
    };

    // Send invitation email
    await this.sendInvitationEmail(data.email, token, data.organizationId);

    return invitation as Invitation;
  }

  /**
   * Accept invitation
   */
  async acceptInvitation(_token: string, _userData: {
    name?: string;
    password: string;
  }): Promise<{ userId: string; organizationId: string }> {
    // Find invitation by token
    // TODO: Implement when Invitation model is added
    // For now, this is a placeholder
    
    throw new Error('Invitation model not yet implemented in schema');
  }

  /**
   * Get invitation by token
   */
  async getInvitationByToken(_token: string): Promise<Invitation | null> {
    // TODO: Implement when Invitation model is added
    return null;
  }

  /**
   * Get all invitations for an organization
   */
  async getInvitationsByOrganization(_organizationId: string): Promise<Invitation[]> {
    // TODO: Implement when Invitation model is added
    return [];
  }

  /**
   * Cancel/delete invitation
   */
  async cancelInvitation(_invitationId: string): Promise<void> {
    // TODO: Implement when Invitation model is added
  }

  /**
   * Send invitation email
   */
  private async sendInvitationEmail(
    email: string,
    token: string,
    organizationId: string
  ): Promise<void> {
    const organization = await prisma.organization.findUnique({
      where: { id: organizationId },
    });

    const invitationUrl = `${process.env.CLIENT_URL || 'http://localhost:3000'}/auth/accept-invitation?token=${token}`;

    // Email templates are prepared for future use when email service is integrated
    // HTML email template (for future use - currently unused)
    // @ts-expect-error - Template prepared for future email service integration
    const _html = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>Team Invitation - Complyx</title>
        </head>
        <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
          <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
            <h1 style="color: #2563eb;">You've been invited to join ${organization?.name || 'Complyx'}!</h1>
            <p>You've been invited to join the team on Complyx. Click the button below to accept the invitation and create your account.</p>
            <a href="${invitationUrl}" style="display: inline-block; padding: 12px 24px; background-color: #2563eb; color: white; text-decoration: none; border-radius: 5px; margin: 20px 0;">Accept Invitation</a>
            <p>Or copy and paste this link into your browser:</p>
            <p style="word-break: break-all; color: #666;">${invitationUrl}</p>
            <p style="margin-top: 30px; font-size: 12px; color: #666;">This invitation will expire in 7 days.</p>
          </div>
        </body>
      </html>
    `;

    // Plain text email template (for future use - currently unused)
    // @ts-expect-error - Template prepared for future email service integration
    const _text = `
      You've been invited to join ${organization?.name || 'Complyx'}!
      
      You've been invited to join the team on Complyx. Click this link to accept the invitation and create your account:
      
      ${invitationUrl}
      
      This invitation will expire in 7 days.
    `;

    // Use emailService to send (we'll need to add a generic send method)
    // For now, we'll use nodemailer directly or extend emailService
    console.log('Invitation email would be sent:', { email, token, organizationId });
  }
}

export const invitationService = new InvitationService();
